hydra:
  run:
    dir: outputs/one_${hydra.job.config_name}_${calo}-${now:%Y-%m-%d}-${now:%H-%M-%S}
  job:
    chdir: True
calo: eb
pipelines: pipe0
context_variables:
  - probe_pt
  - probe_eta
  - probe_phi
  - probe_fixedGridRhoAll
target_variables:
  - probe_r9
  - probe_s4
  - probe_sieie
  - probe_sieip
  - probe_etaWidth
  - probe_phiWidth
train:
  #size: 1500000
  size: 2048
  batch_size: 2048
test:
  #size: 100000
  size: 2048
  batch_size: 2048
model:
  maf:
    num_steps: 6
    num_transform_blocks: 3
    dropout_probability: 0.0
    use_residual_blocks: True
    batch_norm: True
    hidden_dim: 64
  arqs:
    num_steps: 10
    num_transform_blocks: 4
    dropout_probability: 0.1
    use_residual_blocks: True
    batch_norm: True
    hidden_dim: 300
    num_bins: 32
    tail_bound: 1.0
  activation: relu
  init_identity: True
  transform_type: rq-autoregressive
optimizer:
  learning_rate: 1e-5
  beta1: 0.9
  beta2: 0.999
  weight_decay: 1e-4
distributed: False
#epochs: 1500
epochs: 10
sample_every: 10
checkpoint: null