output:
  save_dir: output
  name: cfg19B
general:
  sample: mc
  calo: eb
  condition_columns:
    - probe_pt
    - probe_eta
    - probe_phi
    - probe_fixedGridRhoAll
  columns:
    - probe_r9
    - probe_s4
    - probe_sieie
    - probe_sieip
  nevents: 1000000
  scaler: qtgaus
base:
  mc_eb:
    load_path: None
    batch_size: 512
    lr: 0.0001
    nepochs: 100
    gclip: 5
    nstack: 6
    nblocks: 6
    nnodes: 64
    tail_bound: 5.0
    nbins: 128
    activation: relu
    coupling: false
    coupling_width: 32
    coupling_depth: 2
  data_eb:
    load_path: None
    batch_size: 512
    lr: 0.0001
    nepochs: 100
    gclip: 5
    nstack: 6
    nblocks: 6
    nnodes: 64
    tail_bound: 5.0
    nbins: 128
    activation: relu
    coupling: false
    coupling_width: 32
    coupling_depth: 2
top_transformer_eb:
  load_path: /work/gallim/devel/CQRRelatedStudies/NormalizingFlow/training/output/cfg19B/top_eb/epoch_28_valloss_4.898.pt
  load_path_data: /work/gallim/devel/CQRRelatedStudies/NormalizingFlow/training/output/cfg19/data_eb/epoch_45_valloss_4.849.pt
  load_path_mc: /work/gallim/devel/CQRRelatedStudies/NormalizingFlow/training/output/cfg19/mc_eb/epoch_40_valloss_4.838.pt
  batch_size: 1024
  lr: 0.0001
  nepochs: 200
  flow4flow: FFFCustom
  direction: alternate
  iteration_steps: 7
  gclip: 5
  nstack: 4
  nblocks: 12
  nnodes: 64
  tail_bound: 5.0
  nbins: 128
  activation: relu
  coupling: false
  coupling_width: 64
  coupling_depth: 3
  penalty: l1
  penalty_weight: 0.1
  anneal: 0
