output:
  save_dir: output
  name: cfg17
general:
  sample: mc
  calo: eb
  condition_columns:
    - probe_pt
    - probe_eta
    - probe_phi
    - probe_fixedGridRhoAll
  columns:
    - probe_r9
    - probe_s4
    - probe_sieie
    - probe_sieip
  nevents: 800000
  scaler: standard
base:
  mc_eb:
    load_path: None
    batch_size: 32
    lr: 0.0001
    nepochs: 64
    gclip: 5
    nstack: 6
    nblocks: 6
    nnodes: 64
    tail_bound: 5.0
    nbins: 64
    activation: relu
    coupling: false
    coupling_width: 32
    coupling_depth: 2
  data_eb:
    load_path: None
    batch_size: 32
    lr: 0.0001
    nepochs: 64
    gclip: 5
    nstack: 6
    nblocks: 6
    nnodes: 64
    tail_bound: 5.0
    nbins: 64
    activation: relu
    coupling: false
    coupling_width: 32
    coupling_depth: 2
top_transformer_eb:
  load_path: None
  load_path_data: /work/gallim/devel/CQRRelatedStudies/NormalizingFlow/training/output/cfg16/data_eb/epoch_50_valloss_3.436.pt
  load_path_mc: /work/gallim/devel/CQRRelatedStudies/NormalizingFlow/training/output/cfg16/mc_eb/epoch_46_valloss_3.647.pt
  batch_size: 1024
  lr: 0.0001
  nepochs: 200
  flow4flow: FFFCustom
  direction: alternate
  iteration_steps: 5
  gclip: 5
  nstack: 4
  nblocks: 12
  nnodes: 64
  tail_bound: 5.0
  nbins: 32
  activation: relu
  coupling: false
  coupling_width: 64
  coupling_depth: 3
  penalty: l1
  penalty_weight: 0.1
  anneal: 0
