output:
  save_dir: output
  name: cfg1
general:
  sample: mc
  calo: eb
  condition_columns:
    - probe_pt
  columns:
    - probe_r9
    - probe_s4
  nevents: 100000
base:
  mc_eb:
    load_path: None
    batch_size: 128
    lr: 0.0001
    nepochs: 20
    gclip: 5
    nstack: 10
    nblocks: 5
    nnodes: 128
    tail_bound: 4.0
    nbins: 40
    activation: relu
    coupling: false
    coupling_width: 32
    coupling_depth: 2
  data_eb:
    load_path: None
    batch_size: 128
    lr: 0.0001
    nepochs: 20
    gclip: 5
    nstack: 10
    nblocks: 5
    nnodes: 128
    tail_bound: 4.0
    nbins: 40
    activation: relu
    coupling: false
    coupling_width: 32
    coupling_depth: 2
