output:
  save_dir: output
  name: cfg7_1
general:
  sample: mc
  calo: eb
  condition_columns:
    - probe_pt
    - probe_eta
    - probe_phi
    - probe_fixedGridRhoAll
  columns:
    - probe_r9
    - probe_s4
    - probe_sieie
    - probe_sieip
  nevents: 100000
base:
  mc_eb:
    load_path: /work/gallim/devel/CQRRelatedStudies/NormalizingFlow/training/output/cfg7/mc_eb/epoch_20_valloss_3.717.pt
    train_scaler: /work/gallim/devel/CQRRelatedStudies/NormalizingFlow/training/output/cfg7/mc_eb_train_scaler.save
    val_scaler: /work/gallim/devel/CQRRelatedStudies/NormalizingFlow/training/output/cfg7/mc_eb_val_scaler.save
    batch_size: 32
    lr: 0.0001
    nepochs: 20
    gclip: 5
    nstack: 6
    nblocks: 6
    nnodes: 64
    tail_bound: 4.0
    nbins: 30
    activation: relu
    coupling: false
    coupling_width: 32
    coupling_depth: 2
  data_eb:
    load_path: /work/gallim/devel/CQRRelatedStudies/NormalizingFlow/training/output/cfg7/data_eb/epoch_19_valloss_3.492.pt
    train_scaler: /work/gallim/devel/CQRRelatedStudies/NormalizingFlow/training/output/cfg7/data_eb_train_scaler.save
    val_scaler: /work/gallim/devel/CQRRelatedStudies/NormalizingFlow/training/output/cfg7/data_eb_val_scaler.save
    batch_size: 32
    lr: 0.0001
    nepochs: 20
    gclip: 5
    nstack: 6
    nblocks: 6
    nnodes: 64
    tail_bound: 4.0
    nbins: 30
    activation: relu
    coupling: false
    coupling_width: 32
    coupling_depth: 2
top_transformer_eb:
  load_path: /work/gallim/devel/CQRRelatedStudies/NormalizingFlow/training/output/cfg7_1/top_eb/epoch_10_valloss_3.862.pt
  load_path_data: /work/gallim/devel/CQRRelatedStudies/NormalizingFlow/training/output/cfg7/data_eb/epoch_19_valloss_3.492.pt
  load_path_mc: /work/gallim/devel/CQRRelatedStudies/NormalizingFlow/training/output/cfg7/mc_eb/epoch_20_valloss_3.717.pt
  batch_size: 128
  lr: 0.0001
  nepochs: 10
  flow4flow: customcontext
  direction: alternate
  iteration_steps: 5
  gclip: 5
  nstack: 4
  nblocks: 2
  nnodes: 64
  nbins: 8
  activation: relu
  coupling: false
  coupling_width: 32
  coupling_depth: 2
  penalty: l1
  penalty_weight: 1
  anneal: 0
