output:
  save_dir: output
  name: cfg7_2
general:
  sample: mc
  calo: eb
  condition_columns:
    - probe_pt
    - probe_eta
    - probe_phi
    - probe_fixedGridRhoAll
  columns:
    - probe_r9
    - probe_s4
    - probe_sieie
    - probe_sieip
  nevents: 100000
base:
  mc_eb:
    load_path: None
    batch_size: 32
    lr: 0.0001
    nepochs: 20
    gclip: 5
    nstack: 6
    nblocks: 6
    nnodes: 64
    tail_bound: 4.0
    nbins: 30
    activation: relu
    coupling: false
    coupling_width: 32
    coupling_depth: 2
  data_eb:
    load_path: None
    batch_size: 32
    lr: 0.0001
    nepochs: 20
    gclip: 5
    nstack: 6
    nblocks: 6
    nnodes: 64
    tail_bound: 4.0
    nbins: 30
    activation: relu
    coupling: false
    coupling_width: 32
    coupling_depth: 2
top_transformer_eb:
  load_path: None
  load_path_data: None
  load_path_mc: None
  batch_size: 128
  lr: 0.0001
  nepochs: 10
  flow4flow: customcontext
  direction: alternate
  iteration_steps: 5
  gclip: 5
  nstack: 4
  nblocks: 2
  nnodes: 64
  nbins: 8
  tail_bound: 6.0
  activation: relu
  coupling: false
  coupling_width: 32
  coupling_depth: 2
  penalty: l1
  penalty_weight: 1
  anneal: 0
